name: Build and Deploy Documentation

# Ejecutar el workflow en eventos específicos
on:
  # Ejecutar en push a la rama principal
  push:
    branches: [ "main", "master", "doc", "docs" ]
  # Ejecutar en pull requests hacia la rama principal
  pull_request:
    branches: [ "main", "master" ]
  # Permitir ejecutar manualmente desde la interfaz de GitHub
  workflow_dispatch:

# Configurar permisos para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo una ejecución concurrente de despliegue
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job para construir la documentación
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para obtener tags para la versión
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    
    - name: Build documentation
      run: |
        cd docs
        make html
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs/build/html

  # Job para desplegar a GitHub Pages (solo en rama principal)
  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2 